export function declarationInventoryFailures(
  expected: ReadonlySet<string>,
  fresh: ReadonlySet<string>,
  committed: ReadonlySet<string>,
): Array<string> {
  const failures: Array<string> = [];
  for (const path of expected) {
    if (!fresh.has(path)) {
      failures.push(`  ${path}: tsc did not generate this file`);
    }
    if (!committed.has(path)) {
      failures.push(`  ${path}: missing from dist/ (not committed)`);
    }
  }
  for (const path of fresh) {
    if (!expected.has(path)) {
      failures.push(`  ${path}: unexpected declaration generated by tsc`);
    }
  }
  for (const path of committed) {
    if (!expected.has(path)) {
      failures.push(`  ${path}: obsolete declaration remains in dist/`);
    }
  }
  return failures;
}