export const HELP_ERROR_CODE = {
  UNSUPPORTED: "HELP_UNSUPPORTED",
  RATE_LIMITED: "HELP_RATE_LIMITED",
  AUTHORIZATION_UNAVAILABLE: "HELP_AUTHORIZATION_UNAVAILABLE",
  TIMEOUT: "HELP_TIMEOUT",
  PROVIDER_UNAVAILABLE: "HELP_PROVIDER_UNAVAILABLE",
  PROVIDER_RATE_LIMITED: "HELP_PROVIDER_RATE_LIMITED",
  INVALID_REQUEST: "HELP_INVALID_REQUEST",
} as const;

export const HELP_ERROR_CODES = [
  HELP_ERROR_CODE.UNSUPPORTED,
  HELP_ERROR_CODE.RATE_LIMITED,
  HELP_ERROR_CODE.AUTHORIZATION_UNAVAILABLE,
  HELP_ERROR_CODE.TIMEOUT,
  HELP_ERROR_CODE.PROVIDER_UNAVAILABLE,
  HELP_ERROR_CODE.PROVIDER_RATE_LIMITED,
  HELP_ERROR_CODE.INVALID_REQUEST,
] as const;

export type HelpErrorCode = typeof HELP_ERROR_CODES[number];

export const HELP_ANSWER_CODE = "HELP_ANSWER" as const;
export const HELP_RESPONSE_CODES = [HELP_ANSWER_CODE, ...HELP_ERROR_CODES] as const;
export type HelpResponseCode = typeof HELP_RESPONSE_CODES[number];

export function isHelpErrorCode(value: unknown): value is HelpErrorCode {
  return typeof value === "string" && (HELP_ERROR_CODES as ReadonlyArray<string>).includes(value);
}