#!/usr/bin/env tsx
/**
 * Probe script: measure Poe relay image size cap empirically.
 *
 * Sends progressively larger synthetic JPEG images to each Poe bot and records
 * the exact byte threshold at which the API returns an error.
 *
 * Usage (from workspace root):
 *   pnpm --filter @workspace/api-server exec tsx scripts/probe-poe-image-limits.ts
 *
 * Or with a specific subset of bots:
 *   pnpm --filter @workspace/api-server exec tsx scripts/probe-poe-image-limits.ts \
 *     --bots "Claude-Sonnet-4.5,Gemini-2.5-Pro"
 *
 * Real-JPEG mode (photographic content instead of COM-padded synthetics):
 *   pnpm --filter @workspace/api-server exec tsx scripts/probe-poe-image-limits.ts \
 *     --bots "Claude-Sonnet-4.5" --real-jpeg
 *
 *   In this mode target sizes are 5 MB, 8 MB, 10 MB, 12 MB, and 15 MB.
 *   Each image is a large noise photograph (random RGB pixels across a large
 *   canvas) encoded as a real JPEG.  JPEG quality is binary-searched so the
 *   encoded file lands within ±5 % of the target byte count.  This tests
 *   whether Anthropic's 10 MB per-image limit applies to the encoded file size
 *   or to some other measure (e.g. decoded pixel buffer).
 *
 * Environment:
 *   POE_API_KEY2  — required; Poe OpenAI-compatible API key
 *
 * Methodology (default):
 *   Each synthetic image is a structurally valid JPEG (1×1 white pixel) with
 *   JPEG COM (comment) markers inserted after the SOI byte to pad the file to
 *   the target size.  This ensures any relay-layer size check sees a correctly
 *   sized JPEG rather than a truncated or corrupt file.
 *
 *   Probing stops for a given bot as soon as the first failure is received,
 *   recording the last-OK and first-fail sizes as the empirical cap bracket.
 *
 * Output:
 *   Human-readable table to stdout.
 *   JSON results written to /tmp/poe-probe-results.json.
 */

import { randomBytes } from "crypto";
import { writeFileSync } from "fs";
import OpenAI from "openai";
import sharp from "sharp";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

const POE_API_KEY = process.env["POE_API_KEY2"];
if (!POE_API_KEY) {
  console.error("ERROR: POE_API_KEY2 is not set");
  process.exit(1);
}

const ALL_BOTS = [
  "Claude-Sonnet-4.5",
  "Gemini-3.1-Pro",
  "Gemini-2.5-Pro",
  "GPT-5-Mini",
];

const DEFAULT_TARGET_SIZES_BYTES = [
  1 * 1024 * 1024,   //  1 MB
  5 * 1024 * 1024,   //  5 MB
  10 * 1024 * 1024,  // 10 MB
  15 * 1024 * 1024,  // 15 MB
  20 * 1024 * 1024,  // 20 MB
];

const REAL_JPEG_TARGET_SIZES_BYTES = [
  5 * 1024 * 1024,   //  5 MB
  8 * 1024 * 1024,   //  8 MB
  10 * 1024 * 1024,  // 10 MB
  12 * 1024 * 1024,  // 12 MB
  15 * 1024 * 1024,  // 15 MB
];

/** Per-request timeout (ms) — generous to allow large payloads to upload. */
const REQUEST_TIMEOUT_MS = 90_000;

// Parse --bots CLI arg (e.g. --bots "Claude-Sonnet-4.5,Gemini-2.5-Pro")
const botsArgIdx = process.argv.indexOf("--bots");
const botsArgVal =
  botsArgIdx !== -1
    ? process.argv[botsArgIdx + 1]
    : process.argv.find((a) => a.startsWith("--bots="))?.split("=")[1];
const BOTS: Array<string> = botsArgVal
  ? botsArgVal.split(",").map((s) => s.trim()).filter(Boolean)
  : ALL_BOTS;

// Parse --real-jpeg flag
const REAL_JPEG_MODE = process.argv.includes("--real-jpeg");

const TARGET_SIZES_BYTES = REAL_JPEG_MODE
  ? REAL_JPEG_TARGET_SIZES_BYTES
  : DEFAULT_TARGET_SIZES_BYTES;

// ---------------------------------------------------------------------------
// Poe client
// ---------------------------------------------------------------------------

const client = new OpenAI({
  apiKey: POE_API_KEY,
  baseURL: "https://api.poe.com/v1",
  timeout: REQUEST_TIMEOUT_MS,
  maxRetries: 0,
});

// ---------------------------------------------------------------------------
// Synthetic JPEG builder (COM-padded, default mode)
// ---------------------------------------------------------------------------

/**
 * Build a JPEG buffer padded to approximately `targetBytes` via JPEG COM
 * (comment) markers inserted between the SOI marker and the image body.
 *
 * COM block layout: [0xFF 0xFE] [2-byte BE length = payload+2] [payload zeros]
 * Max payload per COM block: 65533 bytes (length field max = 0xFFFF − 2).
 *
 * The base image is a real 1×1 white JPEG generated by sharp so it passes
 * any JFIF structural validation the relay might perform.
 */
async function buildPaddedJpeg(targetBytes: number): Promise<Buffer> {
  const baseJpeg = await sharp({
    create: {
      width: 1,
      height: 1,
      channels: 3,
      background: { r: 255, g: 255, b: 255 },
    },
  })
    .jpeg({ quality: 80 })
    .toBuffer();

  // SOI = first 2 bytes (0xFF 0xD8); imageBody = everything after SOI
  const soi = baseJpeg.subarray(0, 2);
  const imageBody = baseJpeg.subarray(2);

  const baseSize = soi.length + imageBody.length;
  if (targetBytes <= baseSize) return baseJpeg;

  const MAX_COM_PAYLOAD = 65533;
  const comBlocks: Array<Buffer> = [];
  let remaining = targetBytes - baseSize;

  while (remaining > 0) {
    const blockOverhead = 4; // 2 marker + 2 length
    if (remaining <= blockOverhead) break;
    const payloadSize = Math.min(remaining - blockOverhead, MAX_COM_PAYLOAD);
    const block = Buffer.alloc(blockOverhead + payloadSize, 0);
    block[0] = 0xff;
    block[1] = 0xfe; // COM marker
    block.writeUInt16BE(payloadSize + 2, 2);
    comBlocks.push(block);
    remaining -= blockOverhead + payloadSize;
  }

  return Buffer.concat([soi, ...comBlocks, imageBody]);
}

// ---------------------------------------------------------------------------
// Real photographic JPEG builder (--real-jpeg mode)
// ---------------------------------------------------------------------------

/**
 * Build a real photographic-quality JPEG close to `targetBytes` in size.
 *
 * Strategy:
 *   1. Create a raw random-noise RGB pixel buffer for a large canvas
 *      (3 000 × 3 000 = 27 MP).  Random noise is highly incompressible for
 *      JPEG, so moderate quality settings produce large encoded files that
 *      are structurally indistinguishable from real photographs.
 *   2. Binary-search the JPEG quality value (1–95) so the encoded output
 *      lands within ±5 % of the target byte count.
 *
 * This tests whether Claude's 10 MB per-image limit is measured against the
 * encoded JPEG file size (as documented) or some other quantity such as the
 * decoded pixel buffer (which for a noise image would be ~27 MB regardless
 * of target encode size).
 */
async function buildRealJpeg(targetBytes: number): Promise<Buffer> {
  // Choose canvas size so that quality=95 produces headroom above targetBytes.
  // Empirically: 3000×3000 noise at q=95 ≈ 8.7 MB; 4500×4500 ≈ ~19-20 MB.
  // Use the smallest canvas whose q=95 ceiling clears targetBytes by ≥10%.
  let WIDTH: number;
  let HEIGHT: number;
  if (targetBytes <= 6 * 1024 * 1024) {
    WIDTH = HEIGHT = 3000; // ≈8.7 MB ceiling at q=95 — covers ≤6 MB easily
  } else if (targetBytes <= 10 * 1024 * 1024) {
    WIDTH = HEIGHT = 3500; // ~11-12 MB ceiling at q=95
  } else {
    WIDTH = HEIGHT = 4500; // ~19-20 MB ceiling at q=95 — covers ≤15 MB
  }

  const rawPixels = randomBytes(WIDTH * HEIGHT * 3); // random RGB noise

  const tolerance = targetBytes * 0.05; // ±5 %

  let lo = 1;
  let hi = 95;
  let bestBuf: Buffer | null = null;
  let bestDelta = Infinity;

  for (let iter = 0; iter < 14; iter++) {
    const quality = Math.round((lo + hi) / 2);
    const buf = await sharp(rawPixels, { raw: { width: WIDTH, height: HEIGHT, channels: 3 } })
      .jpeg({ quality })
      .toBuffer();

    const delta = Math.abs(buf.length - targetBytes);
    if (delta < bestDelta) {
      bestDelta = delta;
      bestBuf = buf;
    }

    if (delta <= tolerance) break;

    if (buf.length < targetBytes) {
      lo = quality + 1;
    } else {
      hi = quality - 1;
    }

    if (lo > hi) break;
  }

  if (!bestBuf) throw new Error("Binary search produced no buffer");
  return bestBuf;
}

// ---------------------------------------------------------------------------
// Probe a single bot at a single size
// ---------------------------------------------------------------------------

interface ProbeResult {
  bot: string;
  sizeBytes: number;
  actualBytes: number;
  sizeMB: string;
  ok: boolean;
  skipped: boolean;
  mode: "padded" | "real-jpeg";
  statusCode?: number;
  errorType?: string;
  errorMessage?: string;
  durationMs?: number;
}

async function probeOne(botName: string, sizeBytes: number): Promise<ProbeResult> {
  const sizeMB = (sizeBytes / (1024 * 1024)).toFixed(0) + " MB";
  const modeTag = REAL_JPEG_MODE ? "real-jpeg" : "padded";
  process.stdout.write(`  [${botName}] ${sizeMB.padStart(5)} (${modeTag}) ... `);

  const t0 = Date.now();

  let jpegBuffer: Buffer;
  try {
    jpegBuffer = REAL_JPEG_MODE
      ? await buildRealJpeg(sizeBytes)
      : await buildPaddedJpeg(sizeBytes);
  } catch (buildErr) {
    process.stdout.write("BUILD ERROR\n");
    return {
      bot: botName,
      sizeBytes,
      actualBytes: 0,
      sizeMB,
      ok: false,
      skipped: false,
      mode: modeTag,
      errorType: "BuildError",
      errorMessage: buildErr instanceof Error ? buildErr.message : String(buildErr),
    };
  }

  const actualBytes = jpegBuffer.length;
  const dataUri = `data:image/jpeg;base64,${jpegBuffer.toString("base64")}`;

  try {
    await client.chat.completions.create({
      model: botName,
      max_completion_tokens: 16,
      messages: [
        {
          role: "user",
          content: [
            { type: "image_url", image_url: { url: dataUri } },
            { type: "text", text: "What color is dominant in this image? One word." },
          ] as Array<{ type: "image_url"; image_url: { url: string } } | { type: "text"; text: string }>,
        },
      ],
    });

    const durationMs = Date.now() - t0;
    process.stdout.write(
      `OK   (${(durationMs / 1000).toFixed(1)}s, actual ${(actualBytes / (1024 * 1024)).toFixed(2)} MB)\n`,
    );
    return { bot: botName, sizeBytes, actualBytes, sizeMB, ok: true, skipped: false, mode: modeTag, durationMs };
  } catch (err: unknown) {
    const durationMs = Date.now() - t0;
    const statusCode =
      err != null && typeof err === "object" && "status" in err
        ? (err as { status: number }).status
        : undefined;
    const errorMessage = err instanceof Error ? err.message : String(err);
    const errorType = err instanceof Error ? err.constructor.name : "unknown";

    process.stdout.write(
      `FAIL (${(durationMs / 1000).toFixed(1)}s) HTTP ${statusCode ?? "?"} — ${errorMessage.slice(0, 80)}\n`,
    );
    return {
      bot: botName,
      sizeBytes,
      actualBytes,
      sizeMB,
      ok: false,
      skipped: false,
      mode: modeTag,
      statusCode,
      errorType,
      errorMessage,
      durationMs,
    };
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  const startedAt = new Date().toISOString();
  console.log("=== Poe Relay Image Size Probe ===");
  console.log(`Started : ${startedAt}`);
  console.log(`Mode    : ${REAL_JPEG_MODE ? "real-jpeg (photographic noise, binary-search quality)" : "padded (COM-marker synthetic)"}`);
  console.log(`Bots    : ${BOTS.join(", ")}`);
  console.log(`Sizes   : ${TARGET_SIZES_BYTES.map((b) => (b / (1024 * 1024)).toFixed(0) + " MB").join(", ")}`);
  if (REAL_JPEG_MODE) {
    console.log();
    console.log("Note: In real-jpeg mode each image is a 3000×3000 random-noise photograph");
    console.log("      encoded as JPEG (quality binary-searched to ≈target size, ±5%).");
    console.log("      Actual encoded sizes are printed next to each result.");
  }
  console.log();

  const allResults: Array<ProbeResult> = [];

  for (const bot of BOTS) {
    console.log(`\n── ${bot} ──`);
    let hitFailure = false;

    for (const sizeBytes of TARGET_SIZES_BYTES) {
      const sizeMB = (sizeBytes / (1024 * 1024)).toFixed(0) + " MB";

      if (hitFailure) {
        process.stdout.write(`  [${bot}] ${sizeMB.padStart(5)} ... SKIPPED\n`);
        allResults.push({
          bot,
          sizeBytes,
          actualBytes: 0,
          sizeMB,
          ok: false,
          skipped: true,
          mode: REAL_JPEG_MODE ? "real-jpeg" : "padded",
          errorType: "skipped",
          errorMessage: "Skipped — earlier size already failed",
        });
        continue;
      }

      const result = await probeOne(bot, sizeBytes);
      allResults.push(result);
      if (!result.ok) hitFailure = true;
    }
  }

  // ── Results table ──────────────────────────────────────────────────────────

  console.log("\n\n=== RESULTS TABLE ===\n");
  console.log("Bot                  | Size  | Status | HTTP | Duration | Actual");
  console.log("---------------------|-------|--------|------|----------|---------");
  for (const r of allResults) {
    const botPad   = r.bot.padEnd(20);
    const sizePad  = r.sizeMB.padStart(5);
    const status   = r.skipped ? "SKIP  " : r.ok ? " OK   " : " FAIL ";
    const http     = r.statusCode ? String(r.statusCode) : "  —";
    const dur      = r.durationMs != null ? `${(r.durationMs / 1000).toFixed(1)}s` : "  —";
    const actual   = r.actualBytes ? `${(r.actualBytes / (1024 * 1024)).toFixed(2)} MB` : "  —";
    console.log(`${botPad} | ${sizePad} | ${status} | ${http.padEnd(4)} | ${dur.padStart(7)} | ${actual}`);
  }

  // ── Threshold summary ──────────────────────────────────────────────────────

  console.log("\n\n=== THRESHOLD FINDINGS ===\n");
  for (const bot of BOTS) {
    const botResults = allResults.filter((r) => r.bot === bot && !r.skipped);
    const firstFail = botResults.find((r) => !r.ok);
    const lastOk    = [...botResults].reverse().find((r) => r.ok);

    console.log(`${bot}:`);
    if (firstFail) {
      const lastOkStr  = lastOk
        ? `${lastOk.sizeMB} (${(lastOk.actualBytes / (1024 * 1024)).toFixed(2)} MB actual)`
        : "none — fails at smallest test size";
      const failActual = (firstFail.actualBytes / (1024 * 1024)).toFixed(2);
      console.log(`  Last success : ${lastOkStr}`);
      console.log(`  First failure: ${firstFail.sizeMB} (${failActual} MB actual), HTTP ${firstFail.statusCode ?? "?"}`);
      console.log(`  Error        : ${(firstFail.errorMessage ?? "").slice(0, 120)}`);
    } else if (lastOk) {
      console.log(`  All sizes up to ${lastOk.sizeMB} passed — cap > ${lastOk.sizeMB} (or not enforced at relay layer)`);
    } else {
      console.log(`  No results recorded`);
    }
    console.log();
  }

  // ── JSON output ────────────────────────────────────────────────────────────

  const jsonPath = "/tmp/poe-probe-results.json";
  writeFileSync(
    jsonPath,
    JSON.stringify(
      {
        probedAt: startedAt,
        mode: REAL_JPEG_MODE ? "real-jpeg" : "padded",
        bots: BOTS,
        targetSizesBytes: TARGET_SIZES_BYTES,
        results: allResults,
      },
      null,
      2,
    ),
  );
  console.log(`Full JSON results written to: ${jsonPath}`);
}

main().catch((err) => {
  console.error("\nFatal error:", err);
  process.exit(1);
});
