import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  real,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * Canonical tsvector expression for full-text search over the inventory table.
 *
 * Pass an optional SQL table alias (e.g. `'i'`) when using this inside a
 * query; omit it (or pass `''`) for bare column references used in index
 * definitions.
 *
 * **Both** the GIN index below and every FTS WHERE clause / ts_rank_cd call in
 * the API routes must use this function.  Keeping the expression in one place
 * means PostgreSQL can always use the index — any divergence between the index
 * expression and the query expression causes a silent sequential scan.
 */
export function inventoryFtsVector(tableAlias?: string): ReturnType<typeof sql.raw> {
  const p = tableAlias ? `${tableAlias}.` : "";
  return sql.raw(
    `to_tsvector('english', coalesce(${p}vendor,'') || ' ' || coalesce(${p}catalog,'') || ' ' || coalesce(${p}description,'') || ' ' || coalesce(${p}expanded_description,'') || ' ' || immutable_array_to_string(${p}ai_keywords,' '))`,
  );
}

export const inventoryTable = pgTable(
  "inventory",
  {
    id: serial("id").primaryKey(),
    vendor: text("vendor").notNull(),
    catalog: text("catalog").notNull(),
    description: text("description").notNull().default(""),
    binLocations: text("bin_locations")
      .array()
      .notNull()
      .default(sql`ARRAY[]::text[]`),
    aiKeywords: text("ai_keywords")
      .array()
      .notNull()
      .default(sql`ARRAY[]::text[]`),
    /**
     * Keywords that an admin explicitly set via PATCH /inventory/:id/keywords.
     * These are NEVER overwritten by enrichment jobs — they are always merged
     * back into ai_keywords after any AI-generated keyword run.
     * An empty array means no keywords have been pinned for this item.
     */
    pinnedKeywords: text("pinned_keywords")
      .array()
      .notNull()
      .default(sql`ARRAY[]::text[]`),
    // NOT NULL DEFAULT '{}' is intentional — same contract as binLocations.
    // An empty array means "no barcodes assigned" (not unknown); simplifies
    // array-containment queries and avoids null checks throughout the API.
    barcodes: text("barcodes")
      .array()
      .notNull()
      .default(sql`ARRAY[]::text[]`),
    enrichedAt: timestamp("enriched_at"),
    // ── PDF catalog enrichment ────────────────────────────────────────────────
    imageUrl: text("image_url"),
    thumbnailUrl: text("thumbnail_url"),
    imageUrl2: text("image_url_2"),
    thumbnailUrl2: text("thumbnail_url_2"),
    imageSource: text("image_source"),
    imageConfidence: real("image_confidence"),
    previousDescription: text("previous_description"),
    catalogPdfJobId: integer("catalog_pdf_job_id"),
    // ── AI expanded description ───────────────────────────────────────────────
    // Plain-English expansion of the abbreviated description, generated by
    // the admin-only "Expand Descriptions" enrichment job. Never modifies the
    // original description. Null means not yet expanded (or admin discarded it).
    expandedDescription: text("expanded_description"),
    // ── Human-readable size label ─────────────────────────────────────────────
    // Manually entered by admins (e.g. '1/2"', '3/4"', '4" x 2"').
    // Free text, max 100 chars. Null means no size label has been recorded.
    size: text("size"),
    // ── Physical dimensions ──────────────────────────────────────────────────
    // Nullable JSON object: { length?, width?, height?, diameter? } all in mm.
    // Populated via LiDAR scan or manual entry. Kept as jsonb so the schema
    // remains flexible (e.g. future tolerance fields) without another migration.
    dimensions: jsonb("dimensions").$type<{
      length?: number | null;
      width?: number | null;
      height?: number | null;
      diameter?: number | null;
    }>(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("inventory_vendor_catalog_idx").on(table.vendor, table.catalog),
    index("inventory_dimensions_length_idx").using(
      "btree",
      sql`((dimensions->>'length')::numeric)`,
    ),
    index("inventory_dimensions_width_idx").using(
      "btree",
      sql`((dimensions->>'width')::numeric)`,
    ),
    index("inventory_dimensions_height_idx").using(
      "btree",
      sql`((dimensions->>'height')::numeric)`,
    ),
    index("inventory_dimensions_diameter_idx").using(
      "btree",
      sql`((dimensions->>'diameter')::numeric)`,
    ),
    index("idx_inventory_bin_locations_gin").using("gin", table.binLocations),
    // immutable_array_to_string() is the project-wide IMMUTABLE wrapper around
    // array_to_string(arr, sep). PostgreSQL requires IMMUTABLE functions in index
    // expressions; array_to_string is only STABLE so the wrapper (defined in
    // _untracked_0001_fts_ai_keywords.sql) is required. Queries must use the same
    // expression to get the index scan — see inventory route binPrefix filter.
    index("idx_inventory_bin_locs_prefix_trgm").using(
      "gin",
      sql`immutable_array_to_string(bin_locations, E'\n') gin_trgm_ops`,
    ),
    // ── Full-text search GIN index ────────────────────────────────────────────
    // Declared here (not just in raw SQL) so Drizzle's schema diff catches any
    // drift. The expression must stay in sync with the search query in the API
    // routes (inventory route uses plainto_tsquery against the same tsvector).
    // Last rebuilt in migration 0019 to include expanded_description.
    // immutable_array_to_string is defined in _untracked_0001_fts_ai_keywords.sql
    // and must exist in the database before this index can be created.
    index("inventory_fts_idx").using("gin", inventoryFtsVector()),
    // ── Lowercase full-text trigram GIN index ─────────────────────────────────
    // Used exclusively by the uncategorized-browse exclusion query.  The query
    // does:
    //   id NOT IN (SELECT id FROM inventory WHERE lower_fulltext ~ 'kw1|kw2|...')
    // pg_trgm can use this GIN index for regex (~) patterns, so the inner
    // positive match becomes a Bitmap Index Scan instead of a sequential scan,
    // and the outer NOT IN becomes a Hash Anti Join.
    //
    // The expression must exactly match the WHERE clause in the uncategorized
    // browse path in artifacts/api-server/src/routes/inventory.ts so the planner
    // recognises and uses this index.
    //
    // Defined in migration 0032_inventory_fulltext_trgm_idx.sql.
    index("inventory_fulltext_trgm_idx").using(
      "gin",
      sql`lower(vendor || ' ' || catalog || ' ' || description || ' ' || coalesce(expanded_description, '') || ' ' || immutable_array_to_string(ai_keywords, ' ')) gin_trgm_ops`,
    ),
  ],
);

export const insertInventorySchema = createInsertSchema(inventoryTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertInventory = z.infer<typeof insertInventorySchema>;
export type Inventory = typeof inventoryTable.$inferSelect;

// ── Catalog PDF Job ────────────────────────────────────────────────────────────
export const PDF_JOB_STATUS = ["pending", "processing", "done", "done_with_errors", "failed", "cancelled"] as const;
export type PdfJobStatus = (typeof PDF_JOB_STATUS)[number];

export const catalogPdfJobTable = pgTable("catalog_pdf_job", {
  id: serial("id").primaryKey(),
  vendor: text("vendor").notNull(),
  filename: text("filename").notNull(),
  status: text("status").notNull().default("pending"),
  totalPages: integer("total_pages"),
  processedPages: integer("processed_pages").notNull().default(0),
  partsFound: integer("parts_found").notNull().default(0),
  matchedParts: integer("matched_parts").notNull().default(0),
  imagesMatched: integer("images_matched").notNull().default(0),
  unmatchedParts: jsonb("unmatched_parts").$type<Array<{ catalogNumber: string; description: string }>>(),
  startedAt: timestamp("started_at"),
  finishedAt: timestamp("finished_at"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  dismissed: boolean("dismissed").notNull().default(false),
  // ── Chunked-upload support ────────────────────────────────────────────────
  // All nullable — existing single-chunk jobs have NULL for all four fields.
  // parentJobId: set on every child job; null on parent and legacy jobs.
  // chunkIndex / chunkCount: 0-based index of this chunk and total chunk count.
  // pageOffset: number of pages that precede this chunk in the full document.
  parentJobId: integer("parent_job_id"),
  chunkIndex: integer("chunk_index"),
  chunkCount: integer("chunk_count"),
  pageOffset: integer("page_offset"),
},
(table) => [
  // Partial unique index: enforces one child job per (parent_job_id, chunk_index) slot.
  // The WHERE clause excludes parent and legacy single-upload rows (parent_job_id IS NULL)
  // so they are never affected by this constraint.
  uniqueIndex("catalog_pdf_job_parent_chunk_uniq")
    .on(table.parentJobId, table.chunkIndex)
    .where(sql`parent_job_id IS NOT NULL`),
]);

export const insertCatalogPdfJobSchema = createInsertSchema(catalogPdfJobTable).omit({
  id: true,
  createdAt: true,
});
export type InsertCatalogPdfJob = z.infer<typeof insertCatalogPdfJobSchema>;
export type CatalogPdfJob = typeof catalogPdfJobTable.$inferSelect;

export const warehouseZoneTable = pgTable(
  "warehouse_zone",
  {
    id: serial("id").primaryKey(),
    aisleId: text("aisle_id").notNull(),
    sectionNum: integer("section_num"),
    isInventory: boolean("is_inventory").notNull().default(true),
    svgX: real("svg_x").notNull(),
    svgY: real("svg_y").notNull(),
    svgWidth: real("svg_width").notNull(),
    svgHeight: real("svg_height").notNull(),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("warehouse_zone_aisle_section_idx").on(
      table.aisleId,
      table.sectionNum,
    ),
  ],
);

export const insertWarehouseZoneSchema = createInsertSchema(warehouseZoneTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertWarehouseZone = z.infer<typeof insertWarehouseZoneSchema>;
export type WarehouseZone = typeof warehouseZoneTable.$inferSelect;
